/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c DBusSettingsAdaptor -a dbus_settings_adaptor.h:dbus_settings_adaptor.cpp DBusSettings.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbus_settings_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DBusSettingsAdaptor
 */

DBusSettingsAdaptor::DBusSettingsAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DBusSettingsAdaptor::~DBusSettingsAdaptor()
{
    // destructor
}

int DBusSettingsAdaptor::AddSetting(const QString &group, const QString &name, const QDBusVariant &defaultValue, const QString &itemType, const QDBusVariant &minimum, const QDBusVariant &maximum)
{
    // handle method call com.victronenergy.Settings.AddSetting
    int out0;
    QMetaObject::invokeMethod(parent(), "AddSetting", Q_RETURN_ARG(int, out0), Q_ARG(QString, group), Q_ARG(QString, name), Q_ARG(QDBusVariant, defaultValue), Q_ARG(QString, itemType), Q_ARG(QDBusVariant, minimum), Q_ARG(QDBusVariant, maximum));
    return out0;
}

