/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c DBusSettingsAdaptor -a dbus_settings_adaptor.h:dbus_settings_adaptor.cpp DBusSettings.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUS_SETTINGS_ADAPTOR_H_1418889878
#define DBUS_SETTINGS_ADAPTOR_H_1418889878

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.victronenergy.Settings
 */
class DBusSettingsAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.victronenergy.Settings")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.victronenergy.Settings\">\n"
"    <method name=\"AddSetting\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"group\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"      <arg direction=\"in\" type=\"v\" name=\"defaultValue\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"itemType\"/>\n"
"      <arg direction=\"in\" type=\"v\" name=\"minimum\"/>\n"
"      <arg direction=\"in\" type=\"v\" name=\"maximum\"/>\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <signal name=\"ObjectPathsChanged\"/>\n"
"  </interface>\n"
        "")
public:
    DBusSettingsAdaptor(QObject *parent);
    virtual ~DBusSettingsAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int AddSetting(const QString &group, const QString &name, const QDBusVariant &defaultValue, const QString &itemType, const QDBusVariant &minimum, const QDBusVariant &maximum);
Q_SIGNALS: // SIGNALS
    void ObjectPathsChanged();
};

#endif
